/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.workareas.RegistrarRole;
import javax.swing.table.DefaultTableModel;
import info5100.university.example.workareas.RegistrarRole.shared.RegistrarDataStore;
import java.util.*;

/**
 *
 * @author xuanliliu
 */
public class GradeManagementPanel extends javax.swing.JPanel {
    
    private final RegistrarDataStore ds = RegistrarDataStore.getInstance();

// 学生列表（简单内存表；你也可以改为从别处获取）
private final java.util.List<Object[]> allStudents = new java.util.ArrayList<Object[]>();
// 例如：{ "S10001", "Alice Wang", "MSIS" }

// 当前选择
private String currentSid = null;

    /**
     * Creates new form GradeManagementPanel
     */
    public GradeManagementPanel() {
        initComponents();
        // 初始化 DataStore（仅首次）
ds.seedDemoDataIfEmpty();
ds.seedStudentsIfEmpty();

// 1) Letter 下拉
cmbLetter.removeAllItems();
for (String s : RegistrarDataStore.LETTERS) cmbLetter.addItem(s);

// 2) 表只读和单选
tblStudents.setDefaultEditor(Object.class, null);
tblEnrolledCourses.setDefaultEditor(Object.class, null);
tblGrades.setDefaultEditor(Object.class, null);

tblStudents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
tblEnrolledCourses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
tblGrades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

// 3) 表头列模型
DefaultTableModel ms = (DefaultTableModel) tblStudents.getModel();
ms.setColumnIdentifiers(new String[]{"Student ID","Name","Program"});

DefaultTableModel mc = (DefaultTableModel) tblEnrolledCourses.getModel();
mc.setColumnIdentifiers(new String[]{"Course ID","Title","Term"});

DefaultTableModel mg = (DefaultTableModel) tblGrades.getModel();
mg.setColumnIdentifiers(new String[]{"Course ID","Letter"});

// 4) 种子学生（你可以替换为真实来源）
allStudents.clear();
allStudents.add(new Object[]{"S10001","Alice Wang","MSIS"});
allStudents.add(new Object[]{"S10002","Bob Kim","MSCS"});
allStudents.add(new Object[]{"S10003","Carol Li","MSIS"});

// 5) 载入学生表
reloadStudentTable(allStudents);

    }
    /** 重载学生表 */
private void reloadStudentTable(java.util.List<Object[]> rows){
    DefaultTableModel m = (DefaultTableModel) tblStudents.getModel();
    m.setRowCount(0);
    for (Object[] r : rows) m.addRow(r);
}

/** 当前选中学生ID */
private String getSelectedStudentId() {
    int r = tblStudents.getSelectedRow();
    if (r < 0) return null;
    Object v = tblStudents.getValueAt(r, 0);
    return v == null ? null : v.toString();
}

/** 当前选中课程ID（右上表） */
private String getSelectedCourseId() {
    int r = tblEnrolledCourses.getSelectedRow();
    if (r < 0) return null;
    Object v = tblEnrolledCourses.getValueAt(r, 0);
    return v == null ? null : v.toString();
}

/** 载入某学生已选课程（右上表） */
private void reloadCoursesForStudent(String sid){
    DefaultTableModel m = (DefaultTableModel) tblEnrolledCourses.getModel();
    m.setRowCount(0);
    if (sid == null) return;
    java.util.Set<String> cids = ds.getCoursesOfStudent(sid);
    for (String cid : cids){
        RegistrarDataStore.Offering o = ds.getOfferingById(cid);
        if (o != null){
            m.addRow(new Object[]{o.courseId, o.title, o.term});
        }
    }
}

/** 载入某学生成绩（右下表） */
private void reloadGradesForStudent(String sid){
    DefaultTableModel m = (DefaultTableModel) tblGrades.getModel();
    m.setRowCount(0);
    if (sid == null) return;
    java.util.Map<String,String> g = ds.getGradesOfStudent(sid);
    for (java.util.Map.Entry<String,String> e : g.entrySet()){
        m.addRow(new Object[]{e.getKey(), e.getValue()});
    }
}

/** 简单提示 */
private void info(String s){ javax.swing.JOptionPane.showMessageDialog(this, s, "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE); }
private void warn(String s){ javax.swing.JOptionPane.showMessageDialog(this, s, "Warning", javax.swing.JOptionPane.WARNING_MESSAGE); }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbLetter = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEnrolledCourses = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGrades = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Student");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Letter");

        cmbLetter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTopLayout.createSequentialGroup()
                                .addComponent(txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRefresh)
                                    .addComponent(jButton1)))))
                    .addComponent(btnSave))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnRefresh))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(panelTop, java.awt.BorderLayout.PAGE_START);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Program"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        jSplitPane1.setLeftComponent(jScrollPane1);

        tblEnrolledCourses.setAutoCreateRowSorter(true);
        tblEnrolledCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Term"
            }
        ));
        jScrollPane3.setViewportView(tblEnrolledCourses);

        jScrollPane2.setViewportView(jScrollPane3);

        jSplitPane2.setLeftComponent(jScrollPane2);

        tblGrades.setAutoCreateRowSorter(true);
        tblGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course ID", "Letter"
            }
        ));
        jScrollPane4.setViewportView(tblGrades);

        jSplitPane2.setRightComponent(jScrollPane4);

        jSplitPane1.setRightComponent(jSplitPane2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String q = txtStudentSearch.getText();
    if (q == null || q.trim().isEmpty()){
        reloadStudentTable(allStudents);
        return;
    }
    String needle = q.trim().toLowerCase();
    java.util.List<Object[]> out = new java.util.ArrayList<Object[]>();
    for (Object[] r : allStudents){
        String id = String.valueOf(r[0]).toLowerCase();
        String name = String.valueOf(r[1]).toLowerCase();
        String prog = String.valueOf(r[2]).toLowerCase();
        if (id.contains(needle) || name.contains(needle) || prog.contains(needle)) out.add(r);
    }
    reloadStudentTable(out);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String sid = currentSid != null ? currentSid : getSelectedStudentId();
    if (sid == null){ warn("Please select a student."); return; }
    String cid = getSelectedCourseId();
    if (cid == null){ warn("Please select a course on the right-top table."); return; }
    Object sel = cmbLetter.getSelectedItem();
    if (sel == null){ warn("Please choose a letter grade."); return; }
    String letter = sel.toString();

    String r = ds.recordGrade(sid, cid, letter);
    if (!"OK".equals(r)){ warn(r); return; }

    reloadGradesForStudent(sid);
    info("Saved grade " + letter + " for " + sid + " / " + cid + ".");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        reloadStudentTable(allStudents); // 学生表
    if (currentSid != null){
        reloadCoursesForStudent(currentSid);
        reloadGradesForStudent(currentSid);
    }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        // TODO add your handling code here:
        currentSid = getSelectedStudentId();
    reloadCoursesForStudent(currentSid);
    reloadGradesForStudent(currentSid);
    }//GEN-LAST:event_tblStudentsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbLetter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTable tblEnrolledCourses;
    private javax.swing.JTable tblGrades;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtStudentSearch;
    // End of variables declaration//GEN-END:variables
}
