/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.workareas.RegistrarRole;
import info5100.university.example.workareas.RegistrarRole.shared.RegistrarDataStore;

/**
 *
 * @author xuanliliu
 */
public class RegistrarReportsPanel extends javax.swing.JPanel {
    private final RegistrarDataStore ds = RegistrarDataStore.getInstance();
    
    static class CourseStat {
    String term, dept, cid, name, faculty;
    int enrolled;
    CourseStat(String term, String dept, String cid, String name, String faculty, int enrolled){
        this.term=term; this.dept=dept; this.cid=cid; this.name=name; this.faculty=faculty; this.enrolled=enrolled;
    }
}
    private final java.util.List<CourseStat> courseStats = new java.util.ArrayList<>();

private void info(String s){ javax.swing.JOptionPane.showMessageDialog(this, s, "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE); }
private void warn(String s){ javax.swing.JOptionPane.showMessageDialog(this, s, "Warning", javax.swing.JOptionPane.WARNING_MESSAGE); }

    /**
     * Creates new form RegistrarReportsPanel
     */
    public RegistrarReportsPanel() {
        initComponents();
//        if (cmbTermReport.getItemCount() == 0){
//    cmbTermReport.addItem("Fall 2025");
//    cmbTermReport.addItem("Spring 2026");
//}
    cmbTermReport.setModel(new javax.swing.DefaultComboBoxModel<>());
    reloadTermsFromDS();
    tblEnrollByCourse.setDefaultEditor(Object.class, null);
    tblGpaDist.setDefaultEditor(Object.class, null);
    tblEnrollByCourse.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    @Override
public void addNotify() {
    super.addNotify();
    reloadTermsFromDS(); // 每次显示时刷新学期列表
}{
    // ：确保切 Tab 时也刷新
    this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override public void componentShown(java.awt.event.ComponentEvent e) {
            reloadTermsFromDS();
        }
    });
}

    private void refreshEnrollByCourse(String term){
    javax.swing.table.DefaultTableModel m =
        (javax.swing.table.DefaultTableModel) tblEnrollByCourse.getModel();
    m.setRowCount(0);
    m.setColumnIdentifiers(new String[]{
        "Term","Department","Course ID","Course Name","Faculty","Enrollment Count"
    });
    for (RegistrarDataStore.CourseStat cs : ds.getCourseStats(term)) {
        m.addRow(new Object[]{cs.term, cs.dept, cs.courseId, cs.title, cs.faculty, cs.enrolled});
    }
}

private void reloadTermsFromDS() {
    String prev = (String) cmbTermReport.getSelectedItem();  // 记住当前选择
    javax.swing.DefaultComboBoxModel<String> m = new javax.swing.DefaultComboBoxModel<>();
    for (String t : ds.getAllTerms()) m.addElement(t);
    if (m.getSize() == 0) m.addElement("No Terms");
    cmbTermReport.setModel(m);
    if (prev != null) cmbTermReport.setSelectedItem(prev);   // 恢复选择（如果还存在）
}



private void refreshGpaDist(String term){
    // 这里用固定演示数据，你也可以根据 term 做不同分布
    javax.swing.table.DefaultTableModel m = (javax.swing.table.DefaultTableModel) tblGpaDist.getModel();
    m.setRowCount(0);
    m.setColumnIdentifiers(new String[]{"Program","A","A-","B+","B","B-","C+","C","C-","F","Average GPA"});
    if ("Fall 2025".equals(term)){
        m.addRow(new Object[]{"MSIS", 25,18,14,9,4,2,1,0,0, 3.42});
        m.addRow(new Object[]{"MSCS", 12,15,20,10,6,3,1,0,1, 3.18});
    } else {
        m.addRow(new Object[]{"MSIS", 10,12,11,8,5,3,2,1,0, 3.10});
        m.addRow(new Object[]{"MSCS", 8,9,12,7,6,4,2,1,1,  2.98});
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTermReport = new javax.swing.JComboBox<>();
        btnLoadReports = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnrollByCourse = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGpaDist = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Term");

        cmbTermReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2025", "Spring 2026" }));

        btnLoadReports.setText("Load Reports");
        btnLoadReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(cmbTermReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnLoadReports)))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTermReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLoadReports)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblEnrollByCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Term", "Department", "Course ID", "Course Name", "Faculty", "Enrollment Count"
            }
        ));
        jScrollPane1.setViewportView(tblEnrollByCourse);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enrollment by Course", jPanel2);

        tblGpaDist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Program", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "F", "Average"
            }
        ));
        jScrollPane2.setViewportView(tblGpaDist);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GPA Distribution", jPanel3);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadReportsActionPerformed
        // TODO add your handling code here:
         reloadTermsFromDS();

    Object t = cmbTermReport.getSelectedItem();
    if (t == null && cmbTermReport.getItemCount() > 0) {
        cmbTermReport.setSelectedIndex(0);
        t = cmbTermReport.getSelectedItem();
    }
    if (t == null) { warn("No available terms."); return; }

    String term = t.toString();

    // ★ 不再往 courseStats 手工塞演示数据 ★
    // 直接用 DataStore 生成“按课程的选课统计”
    refreshEnrollByCourse(term);

    // GPA 这块如果你暂时还用示例分布，可以保留，但建议以后也改为从数据推导
    refreshGpaDist(term);

    info("Reports loaded for " + term + ".");
    }//GEN-LAST:event_btnLoadReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadReports;
    private javax.swing.JComboBox<String> cmbTermReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblEnrollByCourse;
    private javax.swing.JTable tblGpaDist;
    // End of variables declaration//GEN-END:variables
}
