/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;



import info5100.university.example.College.College;
import info5100.university.example.Department.Department;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Department department;
    College college;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public AdminRoleWorkAreaJPanel(College c, Department d, JPanel clp) {
        college = c;
        department = d;
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMUA111 = new javax.swing.JButton();
        btnRP = new javax.swing.JButton();
        btnMP = new javax.swing.JButton();
        btnMS = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnAD = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnMF111 = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnMUA111.setBackground(new java.awt.Color(102, 153, 255));
        btnMUA111.setFont(getFont());
        btnMUA111.setForeground(new java.awt.Color(255, 255, 255));
        btnMUA111.setText("Manage User Accounts");
        btnMUA111.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMUA111.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMUA111.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMUA111.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMUA111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUA111IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRP.setBackground(new java.awt.Color(102, 153, 255));
        btnRP.setFont(getFont());
        btnRP.setForeground(new java.awt.Color(255, 255, 255));
        btnRP.setText("Register  Persons (HR)");
        btnRP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRP.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRP.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRP.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPActionPerformed(evt);
            }
        });

        btnMP.setBackground(new java.awt.Color(102, 153, 255));
        btnMP.setFont(getFont());
        btnMP.setForeground(new java.awt.Color(255, 255, 255));
        btnMP.setText("My Profile");
        btnMP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMP.setMaximumSize(new java.awt.Dimension(145, 40));
        btnMP.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMP.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPIdentifyEventsActionPerformed(evt);
            }
        });

        btnMS.setBackground(new java.awt.Color(102, 153, 255));
        btnMS.setFont(getFont());
        btnMS.setForeground(new java.awt.Color(255, 255, 255));
        btnMS.setText("Manage Students");
        btnMS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMS.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMS.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMS.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSActionPerformed(evt);
            }
        });

        btnMR.setBackground(new java.awt.Color(102, 153, 255));
        btnMR.setFont(getFont());
        btnMR.setForeground(new java.awt.Color(255, 255, 255));
        btnMR.setText("Manage Registrar");
        btnMR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMR.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMR.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMR.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });

        btnAD.setBackground(new java.awt.Color(102, 153, 255));
        btnAD.setFont(getFont());
        btnAD.setForeground(new java.awt.Color(255, 255, 255));
        btnAD.setText("Analytics Dashboard");
        btnAD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAD.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAD.setMinimumSize(new java.awt.Dimension(20, 20));
        btnAD.setPreferredSize(new java.awt.Dimension(240, 25));
        btnAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADActionPerformed(evt);
            }
        });

        btnLogOut.setText("log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnMF111.setBackground(new java.awt.Color(102, 153, 255));
        btnMF111.setFont(getFont());
        btnMF111.setForeground(new java.awt.Color(255, 255, 255));
        btnMF111.setText("Manage Faculties");
        btnMF111.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMF111.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMF111.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMF111.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMF111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMF111IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAD, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMF111, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMUA111, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRP, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogOut)))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnLogOut)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMUA111, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMF111, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnAD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMUA111IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUA111IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageUserAccountsJPanel mua = new ManageUserAccountsJPanel(department, CardSequencePanel);

        CardSequencePanel.add("ManageUserAccountsJPanel", mua);
        //((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ManageUserAccountsJPanel");
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();

    }//GEN-LAST:event_btnMUA111IdentifyResourceAssetsActionPerformed

    private void btnRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPActionPerformed
        // TODO add your handling code here:
        PersonRegistrationJPanel pr = new PersonRegistrationJPanel(department, CardSequencePanel);

        CardSequencePanel.add("PersonRegistrationJPanel", pr);
        //((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "PersonRegistrationJPanel");
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
        

    }//GEN-LAST:event_btnRPActionPerformed

    private void btnMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMSActionPerformed

    private void btnMPIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPIdentifyEventsActionPerformed
    }//GEN-LAST:event_btnMPIdentifyEventsActionPerformed

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnMRActionPerformed

    private void btnADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnADActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
//        CardSequencePanel.remove(this);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "LoginScreen");
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
//        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
//        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMF111IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMF111IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        ManageFacultyJPanel mf = new ManageFacultyJPanel(college, department, CardSequencePanel);

        CardSequencePanel.add("ManageFacultyJPanel", mf);
        //((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ManageFacultyJPanel");
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
        
    }//GEN-LAST:event_btnMF111IdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAD;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMF111;
    private javax.swing.JButton btnMP;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMS;
    private javax.swing.JButton btnMUA111;
    private javax.swing.JButton btnRP;
    // End of variables declaration//GEN-END:variables

}
