/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole;


import info5100.university.example.College.College;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.AdminDirectory;
import info5100.university.example.Persona.AdminProfile;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Faculty.UserAccountDirectory;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Persona.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Department department;
    College college;
    //UserAccount selecteduseraccount;


    public ManageStudentJPanel(College cc, Department dd, JPanel jp) {
        CardSequencePanel = jp;
        college = cc;
        department = dd;
        initComponents();
        //populateRoleCombo();
        refreshTable();

    }

    public void refreshTable() {

//clear supplier table
        int rc = tblStudent.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblStudent.getModel()).removeRow(i);
        }



        StudentDirectory sd = department.getStudentDirectory();

       

        for (StudentProfile sp : sd.getStudentlist()) {
            Person student = sp.getPerson();
            Object[] row = new Object[7];
            row[0] = student;
            row[1] = student.getName();
            row[2] = sp.getDepartment();
            row[3] = student.getEmail();
            row[4] = student.getPhone();
            row[5] = student.getAddress();
            row[6] = sp.getCurrentCourseLoad() == null ? "Not enrolled" : "Enrolled";
            
            ((DefaultTableModel) tblStudent.getModel()).addRow(row);
        }

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchBoxID = new javax.swing.JTextField();
        btnSearchID = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        searchBoxName = new javax.swing.JTextField();
        btnSearchName = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        searchBoxDepartment = new javax.swing.JTextField();
        btnSearchDepartment = new javax.swing.JButton();

        setLayout(null);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 20, 80, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(260, 540, 80, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Student Records");
        add(jLabel1);
        jLabel1.setBounds(30, 60, 190, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Student Records");
        add(jLabel2);
        jLabel2.setBounds(170, 20, 280, 28);

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Department", "Email", "Phone", "Address", "Academic Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblStudentMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudent);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 1120, 440);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView);
        btnView.setBounds(30, 540, 78, 23);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(140, 540, 75, 23);

        jLabel3.setText("Seach by ID");
        add(jLabel3);
        jLabel3.setBounds(30, 580, 71, 17);

        searchBoxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxIDActionPerformed(evt);
            }
        });
        add(searchBoxID);
        searchBoxID.setBounds(210, 580, 270, 23);

        btnSearchID.setText("Search ID");
        btnSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDActionPerformed(evt);
            }
        });
        add(btnSearchID);
        btnSearchID.setBounds(510, 580, 110, 23);

        jLabel4.setText("Seach by Name");
        add(jLabel4);
        jLabel4.setBounds(30, 620, 93, 17);

        searchBoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxNameActionPerformed(evt);
            }
        });
        add(searchBoxName);
        searchBoxName.setBounds(210, 620, 270, 23);

        btnSearchName.setText("Search Name");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });
        add(btnSearchName);
        btnSearchName.setBounds(510, 620, 108, 23);

        jLabel5.setText("Seach by Department");
        add(jLabel5);
        jLabel5.setBounds(30, 660, 150, 17);

        searchBoxDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxDepartmentActionPerformed(evt);
            }
        });
        add(searchBoxDepartment);
        searchBoxDepartment.setBounds(210, 660, 270, 23);

        btnSearchDepartment.setText("Search Department");
        btnSearchDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDepartmentActionPerformed(evt);
            }
        });
        add(btnSearchDepartment);
        btnSearchDepartment.setBounds(510, 660, 150, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Admin");
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStudent.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "You sure you want to delete this student?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Person selectedStudent = (Person) tblStudent.getValueAt(selectedRow, 0);
                StudentProfile selectedStudentProfile = department.getStudentDirectory().findStudentID(selectedStudent.getPersonId());
                department.getStudentDirectory().deleteStudent(selectedStudentProfile);
                JOptionPane.showMessageDialog(null, "Student successfully deleted!", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a student from the list", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        refreshTable();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMousePressed

            
    }//GEN-LAST:event_tblStudentMousePressed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStudent.getSelectedRow();
        if (selectedRow >= 0) {
            Person selectedStudent = (Person) tblStudent.getValueAt(selectedRow, 0);
            StudentProfile selectedStudentProfile = department.getStudentDirectory().findStudentID(selectedStudent.getPersonId());
            ViewStudentJPanel vs = new ViewStudentJPanel(CardSequencePanel, college, department, selectedStudentProfile);

            CardSequencePanel.add("ViewStudentJPanel", vs);
            //((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ViewStudentJPanel");
            CardSequencePanel.revalidate();
            CardSequencePanel.repaint();
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a faculty from the list", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void searchBoxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchBoxIDActionPerformed

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDActionPerformed
        // TODO add your handling code here:
        if (!searchBoxID.getText().isBlank()){
            String studentID = searchBoxID.getText();
            StudentProfile foundStudent = department.getStudentDirectory().findStudentID(studentID);
            if (foundStudent != null) {
                populateStudentByID(foundStudent);
            }
            else {
                JOptionPane.showMessageDialog(null, "Student not found! Please try again!", "Warning", JOptionPane.WARNING_MESSAGE);
                clearTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please type in the ID of the student.", "Warning", JOptionPane.WARNING_MESSAGE);
            clearTable();
        }
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void searchBoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxNameActionPerformed

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        // TODO add your handling code here:
        if (!searchBoxName.getText().isBlank()){
            String studentName = searchBoxName.getText();
            ArrayList<StudentProfile> foundStudents = department.getStudentDirectory().searchStudentByName(studentName);
            if (foundStudents != null) {
                populateStudentByName(foundStudents);
            }
            else {
                JOptionPane.showMessageDialog(null, "Student not found! Please try again!", "Warning", JOptionPane.WARNING_MESSAGE);
                clearTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please type in a student's name", "Warning", JOptionPane.WARNING_MESSAGE);
            clearTable();
        }
    }//GEN-LAST:event_btnSearchNameActionPerformed

    private void searchBoxDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxDepartmentActionPerformed

    private void btnSearchDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDepartmentActionPerformed
        // TODO add your handling code here:
        if (!searchBoxDepartment.getText().isBlank()){
            String departmentName = searchBoxDepartment.getText();
            Department foundDepartment = college.findDepartment(departmentName);
            if (foundDepartment != null) {
                //System.out.println("Department found! " + departmentName);
                populateStudentByDepartment(foundDepartment);
            }
            else {
                JOptionPane.showMessageDialog(null, "Department not found! Please try again!", "Warning", JOptionPane.WARNING_MESSAGE);
                clearTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please type in a department", "Warning", JOptionPane.WARNING_MESSAGE);
            clearTable();
        }
    }//GEN-LAST:event_btnSearchDepartmentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearchDepartment;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchBoxDepartment;
    private javax.swing.JTextField searchBoxID;
    private javax.swing.JTextField searchBoxName;
    private javax.swing.JTable tblStudent;
    // End of variables declaration//GEN-END:variables
    
    public void populateStudentByID(StudentProfile student) {
        DefaultTableModel model1 = (DefaultTableModel) tblStudent.getModel();
        model1.setRowCount(0);
        Object[] row = new Object[6];
        Person studentID = student.getPerson();
        row[0] = studentID;
        row[1] = studentID.getName();
        row[2] = student.getDepartment();
        row[3] = studentID.getEmail();
        row[4] = studentID.getPhone();
        row[5] = studentID.getAddress();
        row[6] = student.getCurrentCourseLoad() == null ? "Not enrolled" : "Enrolled";
        model1.addRow(row);
    }
    
    public void populateStudentByName(ArrayList<StudentProfile> foundStudents) {
        DefaultTableModel model1 = (DefaultTableModel) tblStudent.getModel();
        model1.setRowCount(0);
        for (StudentProfile sp: foundStudents) {
            Object[] row = new Object[6];
            Person student = sp.getPerson();
            row[0] = student;
            row[1] = student.getName();
            row[2] = sp.getDepartment();
            row[3] = student.getEmail();
            row[4] = student.getPhone();
            row[5] = student.getAddress();
            row[6] = sp.getCurrentCourseLoad() == null ? "Not enrolled" : "Enrolled";
            model1.addRow(row);
        }         
    }
    
    public void populateStudentByDepartment(Department foundDepartment) {
        DefaultTableModel model1 = (DefaultTableModel) tblStudent.getModel();
        model1.setRowCount(0);
        
        for (StudentProfile sp: foundDepartment.getStudentDirectory().getStudentlist()) {
            Object[] row = new Object[6];
            Person student = sp.getPerson();
            row[0] = student;
            row[1] = student.getName();
            row[2] = sp.getDepartment();
            row[3] = student.getEmail();
            row[4] = student.getPhone();
            row[5] = student.getAddress();
            row[6] = sp.getCurrentCourseLoad() == null ? "Not enrolled" : "Enrolled";
            
            model1.addRow(row);
        }
    }
    
    public void clearTable() {
        DefaultTableModel model1 = (DefaultTableModel) tblStudent.getModel();
        model1.setRowCount(0);
    }
}

