/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole;


import info5100.university.example.College.College;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.AdminDirectory;
import info5100.university.example.Persona.AdminProfile;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Faculty.UserAccountDirectory;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.Registrar.RegistrarDirectory;
import info5100.university.example.Persona.Registrar.RegistrarProfile;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Persona.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageRegistrarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Department department;
    College college;
    //UserAccount selecteduseraccount;


    public ManageRegistrarJPanel(College cc, Department dd, JPanel jp) {
        CardSequencePanel = jp;
        college = cc;
        department = dd;
        initComponents();
        //populateRoleCombo();
        refreshTable();

    }

    public void refreshTable() {

//clear supplier table
        int rc = tblRegistrar.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblRegistrar.getModel()).removeRow(i);
        }



        RegistrarDirectory rd = department.getRegistrarDirectory();

       

        for (RegistrarProfile rp : rd.getRegistrarList()) {
            Person registrar = rp.getPerson();
            Object[] row = new Object[7];
            row[0] = registrar;
            row[1] = registrar.getName(); //complete this..
            row[2] = rp.getDepartment();
            row[3] = registrar.getEmail();
            row[4] = registrar.getPhone();
            row[5] = registrar.getAddress();
            row[6] = rp.getOfficeHours();

            ((DefaultTableModel) tblRegistrar.getModel()).addRow(row);
        }

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrar = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setLayout(null);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 20, 80, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(650, 660, 80, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Registrar Records");
        add(jLabel1);
        jLabel1.setBounds(30, 50, 190, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Registrar Records");
        add(jLabel2);
        jLabel2.setBounds(170, 20, 310, 28);

        tblRegistrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Department", "Email", "Phone", "Address", "Office Hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblRegistrarMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistrar);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 1000, 570);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView);
        btnView.setBounds(30, 660, 78, 23);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(180, 660, 75, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Admin");
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRegistrar.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "You sure you want to delete this registrar?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Person selectedRegistrar = (Person) tblRegistrar.getValueAt(selectedRow, 0);
                RegistrarProfile selectedRegistrarProfile = department.getRegistrarDirectory().findByEmail(selectedRegistrar.getEmail());
                department.getRegistrarDirectory().deleteRegistrar(selectedRegistrarProfile);
                JOptionPane.showMessageDialog(null, "Registrar successfully deleted!", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a registrar from the list", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        refreshTable();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrarMousePressed

        
            
    }//GEN-LAST:event_tblRegistrarMousePressed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRegistrar.getSelectedRow();
        if (selectedRow >= 0) {
            Person selectedRegistrar = (Person) tblRegistrar.getValueAt(selectedRow, 0);
            RegistrarProfile selectedRegistrarProfile = department.getRegistrarDirectory().findByEmail(selectedRegistrar.getEmail());
            ViewRegistrarJPanel vr = new ViewRegistrarJPanel(CardSequencePanel, college, department, selectedRegistrarProfile);

            CardSequencePanel.add("ViewRegistrarJPanel", vr);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ViewRegistrarJPanel");
            CardSequencePanel.revalidate();
            CardSequencePanel.repaint();
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a registrar from the list", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistrar;
    // End of variables declaration//GEN-END:variables
    
//    private void populateRoleCombo() {
//        cmbRole.removeAllItems();
//        cmbRole.addItem("Student");
//        cmbRole.addItem("Faculty");
//        cmbRole.addItem("Admin");
//    }
}

