/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole;


import info5100.university.example.Department.Department;
import info5100.university.example.Persona.AdminDirectory;
import info5100.university.example.Persona.AdminProfile;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Faculty.UserAccountDirectory;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Persona.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class PersonRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Department department;


    public PersonRegistrationJPanel(Department dd, JPanel jp) {
        CardSequencePanel = jp;
        department = dd;
        initComponents();
        populateRoleCombo();
        //refreshTable();

    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        fieldName = new javax.swing.JTextField();
        lblUsername1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        fieldAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        fieldEmail = new javax.swing.JTextField();
        lblPassword1 = new javax.swing.JLabel();

        setLayout(null);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 20, 80, 23);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(330, 280, 72, 23);

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        add(fieldName);
        fieldName.setBounds(330, 60, 180, 23);

        lblUsername1.setText("Name");
        add(lblUsername1);
        lblUsername1.setBounds(250, 60, 34, 17);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Register ");
        add(jLabel3);
        jLabel3.setBounds(250, 20, 96, 29);

        lblUsername.setText("Phone");
        add(lblUsername);
        lblUsername.setBounds(250, 100, 36, 17);

        fieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPhoneActionPerformed(evt);
            }
        });
        add(fieldPhone);
        fieldPhone.setBounds(330, 100, 180, 23);

        lblPassword.setText("Address");
        add(lblPassword);
        lblPassword.setBounds(250, 180, 60, 17);

        fieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAddressActionPerformed(evt);
            }
        });
        add(fieldAddress);
        fieldAddress.setBounds(330, 180, 180, 23);

        jLabel4.setText("Role");
        add(jLabel4);
        jLabel4.setBounds(250, 220, 49, 17);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbRole);
        cmbRole.setBounds(330, 220, 180, 23);

        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });
        add(fieldEmail);
        fieldEmail.setBounds(330, 140, 180, 23);

        lblPassword1.setText("Email");
        add(lblPassword1);
        lblPassword1.setBounds(250, 140, 32, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //CardSequencePanel.remove(this);
        //((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
 //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Admin");
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String name = fieldName.getText();
        String phone = fieldPhone.getText();
        String address = fieldAddress.getText();
        String email = fieldEmail.getText();
        String role = String.valueOf(cmbRole.getSelectedItem());
        
        PersonDirectory pd = department.getPersonDirectory();
        FacultyDirectory facultyDirectory = department.getFacultydirectory();
        StudentDirectory studentDirectory = department.getStudentDirectory();
        AdminDirectory adminDirectory = department.getAdminDirectory();
        //UserAccountDirectory uadirectory = department.getUseraccountdirectory();
        
        if (name.isBlank() || phone.isBlank() || email.isBlank() || address.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please fill out all fields");
            return;
        }
        
        Person newPerson = new Person();
        String id = newPerson.getPersonId();
        newPerson.setName(name);
        newPerson.setPhone(phone);
        newPerson.setAddress(address);
        pd.getPersonlist().add(newPerson);
        
        
        if (pd.findPersonEmail(email) != null) {
            System.out.println(email);
            JOptionPane.showMessageDialog(null, pd.findPersonEmail(email).getName() + "has already registered with this email, try another email.");
            fieldName.setText("");
            fieldPhone.setText("");
            fieldEmail.setText("");
            fieldAddress.setText("");
            return;
        }
        newPerson.setEmail(email);
        
        if (role == "Student") {
            StudentProfile studentProfile0 = studentDirectory.newStudentProfile(newPerson);
            //UserAccount newUser = uadirectory.newUserAccount(studentProfile0, username, password);
        } else if (role == "Faculty") {
            pd.getPersonlist().add(newPerson);
            FacultyProfile facultyProfile0 = facultyDirectory.newFacultyProfile(newPerson);
            //UserAccount newUser = uadirectory.newUserAccount(facultyProfile0, username, password);
        } else if (role == "Admin") {
            pd.getPersonlist().add(newPerson);
            AdminProfile adminProfile0 = adminDirectory.newAdminProfile(newPerson);
            //UserAccount newUser = uadirectory.newUserAccount(adminProfile0, username, password);
        }
        
        
        
        JOptionPane.showMessageDialog(this, "New person registered! Your ID is " + id + "and your email is " + email, "Success", JOptionPane.INFORMATION_MESSAGE);
        
        fieldName.setText("");
        fieldPhone.setText("");
        fieldEmail.setText("");
        fieldAddress.setText("");
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPhoneActionPerformed

    private void fieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAddressActionPerformed

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    // End of variables declaration//GEN-END:variables
    
    private void populateRoleCombo() {
        cmbRole.removeAllItems();
        cmbRole.addItem("Student");
        cmbRole.addItem("Faculty");
        cmbRole.addItem("Admin");
    }
}

